// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZL6f9L0K16LA882qP7-txvOVOTGdBn4',
    appId: '1:1060710407057:web:86e93a450c3834b1b09830',
    messagingSenderId: '1060710407057',
    projectId: 'fitfat-91077',
    authDomain: 'fitfat-91077.firebaseapp.com',
    storageBucket: 'fitfat-91077.appspot.com',
    measurementId: 'G-K0NRKP9NLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6mzf6MQfjfPrraFklYblKCGLV6iF3FE',
    appId: '1:1060710407057:android:2608669538c09d35b09830',
    messagingSenderId: '1060710407057',
    projectId: 'fitfat-91077',
    storageBucket: 'fitfat-91077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMbBaD6aqd_MM2dnY20y5FfRDt0fgxyaA',
    appId: '1:1060710407057:ios:bfbf2ce9f3e9dc58b09830',
    messagingSenderId: '1060710407057',
    projectId: 'fitfat-91077',
    storageBucket: 'fitfat-91077.appspot.com',
    iosBundleId: 'com.example.fitfat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMbBaD6aqd_MM2dnY20y5FfRDt0fgxyaA',
    appId: '1:1060710407057:ios:bfbf2ce9f3e9dc58b09830',
    messagingSenderId: '1060710407057',
    projectId: 'fitfat-91077',
    storageBucket: 'fitfat-91077.appspot.com',
    iosBundleId: 'com.example.fitfat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ZL6f9L0K16LA882qP7-txvOVOTGdBn4',
    appId: '1:1060710407057:web:ff3f29ba270d2faab09830',
    messagingSenderId: '1060710407057',
    projectId: 'fitfat-91077',
    authDomain: 'fitfat-91077.firebaseapp.com',
    storageBucket: 'fitfat-91077.appspot.com',
    measurementId: 'G-LMKN1Q9NW9',
  );

}